apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
        - image: sa1acrind.azurecr.io/backend:latest
          name: backend
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
          resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app: backend
status: {}
