apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
        - image: sa1acrind.azurecr.io/kafka:latest
          name: kafka
          imagePullPolicy: Always
          ports:
          - containerPort: 80    
          resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kafka
status: {}
