apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ocpp-v2
  name: ocpp-v2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocpp-v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocpp-v2
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
        - image: sa1acrind.azurecr.io/ocpp-v2:latest
          name: ocpp-v2
          imagePullPolicy: Always
          ports:
          - containerPort: 8444
          resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ocpp-v2
  name: ocpp-v2-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8444
  selector:
    app: ocpp-v2
status: {}
