apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: openadr
  name: openadr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openadr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openadr
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - image: sa1acrind.azurecr.io/openadr:latest
        name: openadr
        imagePullPolicy: Always
        ports:
          - containerPort: 8090
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openadr
  name: openadr-service
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8090
  selector:
    app: openadr
status: {}
