subscription_id       = "XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX"
location              = "southeastasia"
name                  = "Virtual Machine"
resource_group_name   = "sa1_test_eic_FarajAnsari"
vm_size               = "Standard_B2ms"