subscription_id       = "664b6097-19f2-42a3-be95-a4a6b4069f6b"
location              = "southeastasia"
name                  = "Virtual Machine"
resource_group_name   = "sa1_dev_eic_ip_implementation"
vm_size               = "Standard_B2ms"